-- Unified dynamic schema + in-place data migration from the Hibernate-era model.
-- Safe on both existing Neon databases and empty installs.

CREATE OR REPLACE FUNCTION hourslot_rename_column(tbl text, oldc text, newc text) RETURNS void AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = tbl AND column_name = oldc
    ) AND NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = tbl AND column_name = newc
    ) THEN
        EXECUTE format('ALTER TABLE %I RENAME COLUMN %I TO %I', tbl, oldc, newc);
    END IF;
END;
$$ LANGUAGE plpgsql;

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email               VARCHAR(255) NOT NULL,
    password_hash       VARCHAR(255) NOT NULL,
    phone_number        VARCHAR(64),
    status              VARCHAR(32)  NOT NULL DEFAULT 'ACTIVE',
    email_verified_at   TIMESTAMPTZ,
    locale              VARCHAR(16),
    timezone            VARCHAR(64),
    last_login_at       TIMESTAMPTZ,
    first_name          VARCHAR(128),
    last_name           VARCHAR(128),
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    deleted_at          TIMESTAMPTZ
);

SELECT hourslot_rename_column('users', 'password', 'password_hash');

ALTER TABLE users ADD COLUMN IF NOT EXISTS password_hash VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_number VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE users ADD COLUMN IF NOT EXISTS email_verified_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS locale VARCHAR(16);
ALTER TABLE users ADD COLUMN IF NOT EXISTS timezone VARCHAR(64);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS first_name VARCHAR(128);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_name VARCHAR(128);
ALTER TABLE users ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS legacy_role VARCHAR(32);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'role'
    ) THEN
        EXECUTE 'UPDATE users SET legacy_role = CAST(role AS TEXT) WHERE legacy_role IS NULL';
    END IF;
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'users' AND column_name = 'active'
    ) THEN
        EXECUTE $sql$
            UPDATE users SET status = CASE WHEN active THEN 'ACTIVE' ELSE 'DISABLED' END
            WHERE status IS NULL OR status = ''
        $sql$;
    END IF;
END $$;

UPDATE users SET status = 'ACTIVE' WHERE status IS NULL OR status = '';
UPDATE users SET created_at = NOW() WHERE created_at IS NULL;

CREATE TABLE IF NOT EXISTS customer_profiles (
    user_id         BIGINT PRIMARY KEY REFERENCES users(id),
    date_of_birth   DATE,
    gender          VARCHAR(32),
    address_line1   VARCHAR(255),
    address_line2   VARCHAR(255),
    city            VARCHAR(128),
    region          VARCHAR(128),
    postal_code     VARCHAR(32),
    country_code    VARCHAR(8),
    metadata        JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ
);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'customers') THEN
        EXECUTE $sql$
            INSERT INTO customer_profiles (user_id, date_of_birth, gender, address_line1, created_at)
            SELECT c.user_id, c.date_of_birth, c.gender, c.address, COALESCE(c.created_at, NOW())
            FROM customers c
            ON CONFLICT (user_id) DO NOTHING
        $sql$;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS auth_refresh_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id),
    token_hash   VARCHAR(128) NOT NULL UNIQUE,
    expires_at   TIMESTAMPTZ NOT NULL,
    revoked_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_agent   VARCHAR(512),
    ip_address   VARCHAR(64)
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id),
    token_hash   VARCHAR(128) NOT NULL UNIQUE,
    expires_at   TIMESTAMPTZ NOT NULL,
    used         BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

SELECT hourslot_rename_column('password_reset_tokens', 'token', 'token_hash');
ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS token_hash VARCHAR(128);
ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS used BOOLEAN DEFAULT FALSE;
ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
ALTER TABLE password_reset_tokens ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

-- Hash any leftover plaintext reset tokens so they match SHA-256 hex lookup.
UPDATE password_reset_tokens
SET token_hash = encode(sha256(convert_to(token_hash, 'UTF8')), 'hex')
WHERE token_hash IS NOT NULL AND length(token_hash) < 64;

-- ---------------------------------------------------------------------------
-- Organizations / businesses / branches / categories
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS organizations (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                        VARCHAR(255) NOT NULL,
    slug                        VARCHAR(255) NOT NULL UNIQUE,
    billing_email               VARCHAR(255),
    status                      VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    stripe_customer_id          VARCHAR(128),
    stripe_connect_account_id   VARCHAR(128),
    default_currency            CHAR(3) NOT NULL DEFAULT 'USD',
    country_code                VARCHAR(8),
    timezone                    VARCHAR(64),
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMPTZ,
    deleted_at                  TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS organization_members (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id  BIGINT NOT NULL REFERENCES organizations(id),
    user_id          BIGINT NOT NULL REFERENCES users(id),
    status           VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    invited_by       BIGINT REFERENCES users(id),
    joined_at        TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    deleted_at       TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS categories (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id       BIGINT REFERENCES categories(id),
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL UNIQUE,
    icon            VARCHAR(128),
    image_url       VARCHAR(512),
    image_media_id  BIGINT,
    search_tags     VARCHAR(512),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order      INT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ
);

ALTER TABLE categories ADD COLUMN IF NOT EXISTS parent_id BIGINT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS icon VARCHAR(128);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image_url VARCHAR(512);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS image_media_id BIGINT;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS search_tags VARCHAR(512);
ALTER TABLE categories ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE categories ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
UPDATE categories SET is_active = TRUE WHERE is_active IS NULL;
UPDATE categories SET sort_order = 0 WHERE sort_order IS NULL;

CREATE TABLE IF NOT EXISTS businesses (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT REFERENCES organizations(id),
    name                 VARCHAR(255) NOT NULL,
    slug                 VARCHAR(255) UNIQUE,
    description          TEXT,
    status               VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    is_verified          BOOLEAN NOT NULL DEFAULT FALSE,
    rejection_reason     VARCHAR(512),
    registration_number  VARCHAR(128),
    primary_category_id  BIGINT REFERENCES categories(id),
    rating_avg           NUMERIC(3,2) NOT NULL DEFAULT 0,
    rating_count         INT NOT NULL DEFAULT 0,
    timezone             VARCHAR(64),
    locale               VARCHAR(16),
    settings             JSONB,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ,
    deleted_at           TIMESTAMPTZ
);

ALTER TABLE businesses ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS status VARCHAR(32);
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS is_verified BOOLEAN;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(512);
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS registration_number VARCHAR(128);
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS primary_category_id BIGINT;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS rating_avg NUMERIC(3,2);
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS rating_count INT;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS timezone VARCHAR(64);
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS locale VARCHAR(16);
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS settings JSONB;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'businesses' AND column_name = 'verified')
       AND EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'businesses' AND column_name = 'is_verified') THEN
        EXECUTE 'UPDATE businesses SET is_verified = COALESCE(is_verified, verified, FALSE)';
    ELSIF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'businesses' AND column_name = 'verified') THEN
        EXECUTE 'ALTER TABLE businesses RENAME COLUMN verified TO is_verified';
    END IF;
END $$;

UPDATE businesses SET is_verified = FALSE WHERE is_verified IS NULL;
UPDATE businesses SET status = 'PENDING' WHERE status IS NULL OR status = '';
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'businesses' AND column_name = 'rating') THEN
        EXECUTE 'UPDATE businesses SET rating_avg = COALESCE(rating, 0) WHERE rating_avg IS NULL';
    END IF;
END $$;
UPDATE businesses SET rating_avg = 0 WHERE rating_avg IS NULL;
UPDATE businesses SET rating_count = 0 WHERE rating_count IS NULL;

-- 1:1 org per existing business owner
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'businesses' AND column_name = 'owner_id') THEN
        EXECUTE $sql$
            INSERT INTO organizations (name, slug, billing_email, status, default_currency, created_at, updated_at)
            SELECT DISTINCT
                COALESCE(NULLIF(b.name, ''), 'Organization') || ' Org',
                'org-' || u.id::text,
                u.email,
                'ACTIVE',
                'USD',
                COALESCE(b.created_at, NOW()),
                NOW()
            FROM businesses b
            JOIN users u ON u.id = b.owner_id
            WHERE NOT EXISTS (SELECT 1 FROM organizations o WHERE o.slug = 'org-' || u.id::text)
        $sql$;
        EXECUTE $sql$
            INSERT INTO organization_members (organization_id, user_id, status, joined_at, created_at)
            SELECT o.id, u.id, 'ACTIVE', NOW(), NOW()
            FROM businesses b
            JOIN users u ON u.id = b.owner_id
            JOIN organizations o ON o.slug = 'org-' || u.id::text
            WHERE NOT EXISTS (
                SELECT 1 FROM organization_members om
                WHERE om.organization_id = o.id AND om.user_id = u.id
            )
        $sql$;
        EXECUTE $sql$
            UPDATE businesses b
            SET organization_id = o.id
            FROM users u, organizations o
            WHERE u.id = b.owner_id
              AND o.slug = 'org-' || u.id::text
              AND b.organization_id IS NULL
        $sql$;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS business_categories (
    business_id  BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    category_id  BIGINT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (business_id, category_id)
);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'business_secondary_categories') THEN
        INSERT INTO business_categories (business_id, category_id)
        SELECT business_id, category_id FROM business_secondary_categories
        ON CONFLICT DO NOTHING;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS branches (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id   BIGINT NOT NULL REFERENCES businesses(id),
    name          VARCHAR(255) NOT NULL,
    address       VARCHAR(512) NOT NULL,
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    phone_number  VARCHAR(64),
    timezone      VARCHAR(64),
    is_active     BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order    INT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ,
    deleted_at    TIMESTAMPTZ
);

ALTER TABLE branches ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS phone_number VARCHAR(64);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS timezone VARCHAR(64);
ALTER TABLE branches ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE branches ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
UPDATE branches SET is_active = TRUE WHERE is_active IS NULL;
UPDATE branches SET sort_order = 0 WHERE sort_order IS NULL;
UPDATE branches SET latitude = 0 WHERE latitude IS NULL;
UPDATE branches SET longitude = 0 WHERE longitude IS NULL;

-- ---------------------------------------------------------------------------
-- Dynamic RBAC / menus
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS permissions (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(128) NOT NULL UNIQUE,
    module       VARCHAR(64) NOT NULL,
    description  VARCHAR(255),
    is_active    BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS roles (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope            VARCHAR(32) NOT NULL,
    organization_id  BIGINT REFERENCES organizations(id),
    business_id      BIGINT REFERENCES businesses(id),
    code             VARCHAR(64) NOT NULL,
    name             VARCHAR(128) NOT NULL,
    is_system        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id        BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    permission_id  BIGINT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE IF NOT EXISTS member_roles (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT NOT NULL REFERENCES users(id),
    role_id          BIGINT NOT NULL REFERENCES roles(id),
    organization_id  BIGINT REFERENCES organizations(id),
    business_id      BIGINT REFERENCES businesses(id),
    branch_id        BIGINT REFERENCES branches(id),
    staff_id         BIGINT,
    granted_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    granted_by       BIGINT REFERENCES users(id),
    expires_at       TIMESTAMPTZ,
    deleted_at       TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS nav_menus (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                       VARCHAR(128) NOT NULL UNIQUE,
    label                      VARCHAR(128) NOT NULL,
    path                       VARCHAR(255),
    icon                       VARCHAR(128),
    parent_id                  BIGINT REFERENCES nav_menus(id),
    sort_order                 INT NOT NULL DEFAULT 0,
    audience                   VARCHAR(32) NOT NULL,
    required_permission_code   VARCHAR(128),
    is_active                  BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS role_menu_items (
    role_id      BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    nav_menu_id  BIGINT NOT NULL REFERENCES nav_menus(id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, nav_menu_id)
);

-- ---------------------------------------------------------------------------
-- Staff / resources / catalog
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS staff (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id      BIGINT NOT NULL REFERENCES branches(id),
    user_id        BIGINT REFERENCES users(id),
    display_name   VARCHAR(255) NOT NULL,
    designation    VARCHAR(128),
    specialty      VARCHAR(255),
    bio            TEXT,
    rating_avg     NUMERIC(3,2) NOT NULL DEFAULT 0,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order     INT NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    deleted_at     TIMESTAMPTZ
);

SELECT hourslot_rename_column('staff', 'name', 'display_name');
ALTER TABLE staff ADD COLUMN IF NOT EXISTS display_name VARCHAR(255);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS specialty VARCHAR(255);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS bio TEXT;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS rating_avg NUMERIC(3,2);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE staff ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'staff' AND column_name = 'rating') THEN
        EXECUTE 'UPDATE staff SET rating_avg = COALESCE(rating, 0) WHERE rating_avg IS NULL';
    END IF;
END $$;
UPDATE staff SET rating_avg = 0 WHERE rating_avg IS NULL;
UPDATE staff SET is_active = TRUE WHERE is_active IS NULL;
UPDATE staff SET sort_order = 0 WHERE sort_order IS NULL;
UPDATE staff SET display_name = 'Staff' WHERE display_name IS NULL OR display_name = '';

CREATE TABLE IF NOT EXISTS resources (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id      BIGINT NOT NULL REFERENCES branches(id),
    name           VARCHAR(255) NOT NULL,
    resource_type  VARCHAR(32) NOT NULL DEFAULT 'OTHER',
    capacity       INT NOT NULL DEFAULT 1,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    metadata       JSONB,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ,
    deleted_at     TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS services (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id        BIGINT NOT NULL REFERENCES businesses(id),
    name               VARCHAR(255) NOT NULL,
    description        TEXT,
    base_price         NUMERIC(12,2) NOT NULL DEFAULT 0,
    currency           CHAR(3) NOT NULL DEFAULT 'USD',
    duration_minutes   INT NOT NULL,
    buffer_minutes     INT NOT NULL DEFAULT 0,
    max_concurrent     INT NOT NULL DEFAULT 1,
    capacity           INT NOT NULL DEFAULT 1,
    is_group_service   BOOLEAN NOT NULL DEFAULT FALSE,
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order         INT NOT NULL DEFAULT 0,
    metadata           JSONB,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMPTZ,
    deleted_at         TIMESTAMPTZ
);

SELECT hourslot_rename_column('services', 'price', 'base_price');
ALTER TABLE services ADD COLUMN IF NOT EXISTS base_price NUMERIC(12,2);
ALTER TABLE services ADD COLUMN IF NOT EXISTS currency CHAR(3) DEFAULT 'USD';
ALTER TABLE services ADD COLUMN IF NOT EXISTS buffer_minutes INT DEFAULT 0;
ALTER TABLE services ADD COLUMN IF NOT EXISTS max_concurrent INT DEFAULT 1;
ALTER TABLE services ADD COLUMN IF NOT EXISTS capacity INT DEFAULT 1;
ALTER TABLE services ADD COLUMN IF NOT EXISTS is_group_service BOOLEAN DEFAULT FALSE;
ALTER TABLE services ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE services ADD COLUMN IF NOT EXISTS sort_order INT DEFAULT 0;
ALTER TABLE services ADD COLUMN IF NOT EXISTS metadata JSONB;
ALTER TABLE services ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE services ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE services ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
UPDATE services SET currency = 'USD' WHERE currency IS NULL;
UPDATE services SET buffer_minutes = 0 WHERE buffer_minutes IS NULL;
UPDATE services SET max_concurrent = 1 WHERE max_concurrent IS NULL;
UPDATE services SET capacity = 1 WHERE capacity IS NULL;
UPDATE services SET is_group_service = FALSE WHERE is_group_service IS NULL;
UPDATE services SET is_active = TRUE WHERE is_active IS NULL;
UPDATE services SET sort_order = 0 WHERE sort_order IS NULL;
UPDATE services SET base_price = 0 WHERE base_price IS NULL;

CREATE TABLE IF NOT EXISTS staff_services (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id        BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    service_id      BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    price_override  NUMERIC(12,2),
    UNIQUE (staff_id, service_id)
);

CREATE TABLE IF NOT EXISTS service_resources (
    service_id   BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    resource_id  BIGINT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
    quantity     INT NOT NULL DEFAULT 1,
    PRIMARY KEY (service_id, resource_id)
);

CREATE TABLE IF NOT EXISTS time_of_day_pricing (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_id         BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    day_of_week        SMALLINT NOT NULL,
    start_time         TIME NOT NULL,
    end_time           TIME NOT NULL,
    price_multiplier   NUMERIC(6,3) NOT NULL DEFAULT 1,
    label              VARCHAR(64),
    is_active          BOOLEAN NOT NULL DEFAULT TRUE
);

ALTER TABLE time_of_day_pricing ADD COLUMN IF NOT EXISTS label VARCHAR(64);
ALTER TABLE time_of_day_pricing ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
UPDATE time_of_day_pricing SET is_active = TRUE WHERE is_active IS NULL;

CREATE TABLE IF NOT EXISTS service_packages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id     BIGINT NOT NULL REFERENCES businesses(id),
    name            VARCHAR(255) NOT NULL,
    description     TEXT,
    price           NUMERIC(12,2) NOT NULL,
    currency        CHAR(3) NOT NULL DEFAULT 'USD',
    sessions_count  INT NOT NULL,
    expiry_days     INT,
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ,
    deleted_at      TIMESTAMPTZ
);

ALTER TABLE service_packages ADD COLUMN IF NOT EXISTS currency CHAR(3) DEFAULT 'USD';
ALTER TABLE service_packages ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;
ALTER TABLE service_packages ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE service_packages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE service_packages ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
UPDATE service_packages SET currency = 'USD' WHERE currency IS NULL;
UPDATE service_packages SET is_active = TRUE WHERE is_active IS NULL;

CREATE TABLE IF NOT EXISTS package_services (
    package_id  BIGINT NOT NULL REFERENCES service_packages(id) ON DELETE CASCADE,
    service_id  BIGINT NOT NULL REFERENCES services(id) ON DELETE CASCADE,
    PRIMARY KEY (package_id, service_id)
);

CREATE TABLE IF NOT EXISTS customer_packages (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_user_id      BIGINT NOT NULL REFERENCES users(id),
    package_id            BIGINT NOT NULL REFERENCES service_packages(id),
    business_id           BIGINT REFERENCES businesses(id),
    sessions_remaining    INT NOT NULL,
    expires_at            TIMESTAMPTZ,
    status                VARCHAR(32) NOT NULL,
    purchase_payment_id   BIGINT,
    version               INT NOT NULL DEFAULT 1,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ
);

ALTER TABLE customer_packages ADD COLUMN IF NOT EXISTS customer_user_id BIGINT;
ALTER TABLE customer_packages ADD COLUMN IF NOT EXISTS business_id BIGINT;
ALTER TABLE customer_packages ADD COLUMN IF NOT EXISTS purchase_payment_id BIGINT;
ALTER TABLE customer_packages ADD COLUMN IF NOT EXISTS version INT DEFAULT 1;
ALTER TABLE customer_packages ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'customer_packages' AND column_name = 'customer_id') THEN
        EXECUTE 'UPDATE customer_packages SET customer_user_id = customer_id WHERE customer_user_id IS NULL';
    END IF;
END $$;
UPDATE customer_packages cp
SET business_id = sp.business_id
FROM service_packages sp
WHERE cp.package_id = sp.id AND cp.business_id IS NULL;
UPDATE customer_packages SET version = 1 WHERE version IS NULL;

-- ---------------------------------------------------------------------------
-- Scheduling
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS branch_working_hours (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id     BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    day_of_week   SMALLINT NOT NULL,
    start_time    TIME,
    end_time      TIME,
    closed        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS branch_breaks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    working_hour_id   BIGINT NOT NULL REFERENCES branch_working_hours(id) ON DELETE CASCADE,
    start_time        TIME NOT NULL,
    end_time          TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS staff_working_hours (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id      BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    day_of_week   SMALLINT NOT NULL,
    start_time    TIME,
    end_time      TIME,
    closed        BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS staff_breaks (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    working_hour_id   BIGINT NOT NULL REFERENCES staff_working_hours(id) ON DELETE CASCADE,
    start_time        TIME NOT NULL,
    end_time          TIME NOT NULL
);

CREATE TABLE IF NOT EXISTS branch_holidays (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    branch_id      BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
    holiday_date   DATE NOT NULL,
    description    VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS staff_time_off (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_id    BIGINT NOT NULL REFERENCES staff(id) ON DELETE CASCADE,
    start_at    TIMESTAMPTZ NOT NULL,
    end_at      TIMESTAMPTZ NOT NULL,
    reason      VARCHAR(255),
    status      VARCHAR(32) NOT NULL DEFAULT 'APPROVED'
);

CREATE TABLE IF NOT EXISTS resource_unavailability (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id  BIGINT NOT NULL REFERENCES resources(id) ON DELETE CASCADE,
    start_at     TIMESTAMPTZ NOT NULL,
    end_at       TIMESTAMPTZ NOT NULL,
    reason       VARCHAR(255)
);

DO $$
DECLARE
    rec RECORD;
    new_id BIGINT;
    br RECORD;
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'working_hours') THEN
        FOR rec IN SELECT * FROM working_hours WHERE staff_id IS NULL LOOP
            INSERT INTO branch_working_hours (branch_id, day_of_week, start_time, end_time, closed)
            VALUES (rec.branch_id, rec.day_of_week, rec.start_time, rec.end_time, rec.closed)
            RETURNING id INTO new_id;
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'breaks') THEN
                INSERT INTO branch_breaks (working_hour_id, start_time, end_time)
                SELECT new_id, start_time, end_time FROM breaks WHERE working_hour_id = rec.id;
            END IF;
        END LOOP;

        FOR rec IN SELECT * FROM working_hours WHERE staff_id IS NOT NULL LOOP
            INSERT INTO staff_working_hours (staff_id, day_of_week, start_time, end_time, closed)
            VALUES (rec.staff_id, rec.day_of_week, rec.start_time, rec.end_time, rec.closed)
            RETURNING id INTO new_id;
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'breaks') THEN
                INSERT INTO staff_breaks (working_hour_id, start_time, end_time)
                SELECT new_id, start_time, end_time FROM breaks WHERE working_hour_id = rec.id;
            END IF;
        END LOOP;
    END IF;

    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'holidays') THEN
        INSERT INTO branch_holidays (branch_id, holiday_date, description)
        SELECT branch_id, date, description FROM holidays WHERE staff_id IS NULL;

        INSERT INTO staff_time_off (staff_id, start_at, end_at, reason, status)
        SELECT staff_id,
               date::timestamp,
               (date + 1)::timestamp - INTERVAL '1 second',
               description,
               'APPROVED'
        FROM holidays
        WHERE staff_id IS NOT NULL;
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Bookings
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS bookings (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_code            VARCHAR(32) UNIQUE,
    customer_user_id       BIGINT REFERENCES users(id),
    organization_id        BIGINT REFERENCES organizations(id),
    business_id            BIGINT REFERENCES businesses(id),
    branch_id              BIGINT NOT NULL REFERENCES branches(id),
    status                 VARCHAR(32) NOT NULL,
    booking_time           TIMESTAMPTZ NOT NULL,
    end_time               TIMESTAMPTZ NOT NULL,
    total_price            NUMERIC(12,2) NOT NULL DEFAULT 0,
    currency               CHAR(3) NOT NULL DEFAULT 'USD',
    payment_status         VARCHAR(32),
    payment_method         VARCHAR(32),
    client_notes           TEXT,
    internal_notes         TEXT,
    source                 VARCHAR(32) NOT NULL DEFAULT 'MARKETPLACE',
    customer_package_id    BIGINT REFERENCES customer_packages(id),
    membership_id          BIGINT,
    deal_id                BIGINT,
    version                INT NOT NULL DEFAULT 1,
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at             TIMESTAMPTZ,
    deleted_at             TIMESTAMPTZ
);

ALTER TABLE bookings ADD COLUMN IF NOT EXISTS public_code VARCHAR(32);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS customer_user_id BIGINT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS organization_id BIGINT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS business_id BIGINT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS total_price NUMERIC(12,2);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS currency CHAR(3) DEFAULT 'USD';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS payment_method VARCHAR(32);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS client_notes TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS internal_notes TEXT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS source VARCHAR(32) DEFAULT 'MARKETPLACE';
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS customer_package_id BIGINT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS membership_id BIGINT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS deal_id BIGINT;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS version INT DEFAULT 1;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'customer_id') THEN
        EXECUTE 'UPDATE bookings SET customer_user_id = customer_id WHERE customer_user_id IS NULL';
    END IF;
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'bookings' AND column_name = 'price') THEN
        EXECUTE 'UPDATE bookings SET total_price = price WHERE total_price IS NULL';
    END IF;
END $$;
UPDATE bookings SET total_price = 0 WHERE total_price IS NULL;
UPDATE bookings SET currency = 'USD' WHERE currency IS NULL;
UPDATE bookings SET source = 'MARKETPLACE' WHERE source IS NULL;
UPDATE bookings SET version = 1 WHERE version IS NULL;
UPDATE bookings SET payment_method = CASE
    WHEN payment_status ILIKE '%PACKAGE%' THEN 'PACKAGE'
    WHEN payment_status ILIKE 'PAID%' THEN 'ONLINE'
    ELSE 'VENUE'
END
WHERE payment_method IS NULL;
UPDATE bookings SET public_code = 'HS' || LPAD(id::text, 8, '0') WHERE public_code IS NULL;

UPDATE bookings b
SET business_id = br.business_id,
    organization_id = biz.organization_id
FROM branches br
JOIN businesses biz ON biz.id = br.business_id
WHERE b.branch_id = br.id
  AND (b.business_id IS NULL OR b.organization_id IS NULL);

CREATE TABLE IF NOT EXISTS booking_items (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id         BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    service_id         BIGINT NOT NULL REFERENCES services(id),
    staff_id           BIGINT REFERENCES staff(id),
    resource_id        BIGINT REFERENCES resources(id),
    start_time         TIMESTAMPTZ NOT NULL,
    end_time           TIMESTAMPTZ NOT NULL,
    unit_price         NUMERIC(12,2) NOT NULL,
    price_multiplier   NUMERIC(6,3) NOT NULL DEFAULT 1,
    line_total         NUMERIC(12,2) NOT NULL,
    sort_order         INT NOT NULL DEFAULT 0
);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'bookings' AND column_name = 'service_id'
    ) THEN
        INSERT INTO booking_items (booking_id, service_id, staff_id, start_time, end_time, unit_price, price_multiplier, line_total, sort_order)
        SELECT b.id, b.service_id, b.staff_id, b.booking_time, b.end_time,
               COALESCE(b.total_price, 0), 1, COALESCE(b.total_price, 0), 0
        FROM bookings b
        WHERE b.service_id IS NOT NULL
          AND NOT EXISTS (SELECT 1 FROM booking_items i WHERE i.booking_id = b.id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS booking_status_history (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id            BIGINT NOT NULL REFERENCES bookings(id) ON DELETE CASCADE,
    from_status           VARCHAR(32),
    to_status             VARCHAR(32) NOT NULL,
    changed_by_user_id    BIGINT REFERENCES users(id),
    reason                VARCHAR(255),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS waitlist_entries (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id           BIGINT NOT NULL REFERENCES businesses(id),
    branch_id             BIGINT NOT NULL REFERENCES branches(id),
    customer_user_id      BIGINT NOT NULL REFERENCES users(id),
    service_id            BIGINT NOT NULL REFERENCES services(id),
    staff_id              BIGINT REFERENCES staff(id),
    preferred_start       TIMESTAMPTZ,
    preferred_end         TIMESTAMPTZ,
    flexibility_minutes   INT,
    status                VARCHAR(32) NOT NULL DEFAULT 'OPEN',
    offered_booking_id    BIGINT REFERENCES bookings(id),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS deals (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id       BIGINT NOT NULL REFERENCES businesses(id),
    branch_id         BIGINT REFERENCES branches(id),
    service_id        BIGINT REFERENCES services(id),
    title             VARCHAR(255) NOT NULL,
    discount_type     VARCHAR(16) NOT NULL,
    discount_value    NUMERIC(12,2) NOT NULL,
    window_start      TIMESTAMPTZ NOT NULL,
    window_end        TIMESTAMPTZ NOT NULL,
    capacity          INT,
    claimed_count     INT NOT NULL DEFAULT 0,
    status            VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ,
    deleted_at        TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS deal_redemptions (
    deal_id            BIGINT NOT NULL REFERENCES deals(id),
    customer_user_id   BIGINT NOT NULL REFERENCES users(id),
    booking_id         BIGINT REFERENCES bookings(id),
    PRIMARY KEY (deal_id, customer_user_id)
);

-- ---------------------------------------------------------------------------
-- Memberships / payments / SaaS
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS membership_plans (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id      BIGINT NOT NULL REFERENCES businesses(id),
    name             VARCHAR(255) NOT NULL,
    description      TEXT,
    billing_period   VARCHAR(16) NOT NULL DEFAULT 'NONE',
    price            NUMERIC(12,2) NOT NULL,
    currency         CHAR(3) NOT NULL DEFAULT 'USD',
    benefits         JSONB,
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ,
    deleted_at       TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS customer_memberships (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_user_id        BIGINT NOT NULL REFERENCES users(id),
    membership_plan_id      BIGINT NOT NULL REFERENCES membership_plans(id),
    business_id             BIGINT NOT NULL REFERENCES businesses(id),
    status                  VARCHAR(32) NOT NULL,
    starts_at               TIMESTAMPTZ,
    ends_at                 TIMESTAMPTZ,
    stripe_subscription_id  VARCHAR(128),
    version                 INT NOT NULL DEFAULT 1,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS payments (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id       BIGINT REFERENCES organizations(id),
    business_id           BIGINT REFERENCES businesses(id),
    user_id               BIGINT REFERENCES users(id),
    purpose               VARCHAR(32) NOT NULL,
    reference_type        VARCHAR(32),
    reference_id          BIGINT,
    provider              VARCHAR(32) NOT NULL DEFAULT 'OTHER',
    provider_payment_id   VARCHAR(128),
    amount                NUMERIC(12,2) NOT NULL,
    currency              CHAR(3) NOT NULL DEFAULT 'USD',
    status                VARCHAR(32) NOT NULL,
    raw_payload           JSONB,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ,
    version               INT NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS payment_refunds (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id          BIGINT NOT NULL REFERENCES payments(id),
    amount              NUMERIC(12,2) NOT NULL,
    reason              VARCHAR(255),
    provider_refund_id  VARCHAR(128),
    status              VARCHAR(32) NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS payment_allocations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id   BIGINT NOT NULL REFERENCES payments(id),
    target_type  VARCHAR(32) NOT NULL,
    target_id    BIGINT NOT NULL,
    amount       NUMERIC(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS subscription_plans (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code               VARCHAR(64) NOT NULL UNIQUE,
    name               VARCHAR(128) NOT NULL,
    billing_interval   VARCHAR(16) NOT NULL,
    price              NUMERIC(12,2) NOT NULL,
    currency           CHAR(3) NOT NULL DEFAULT 'USD',
    stripe_price_id    VARCHAR(128),
    is_active          BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order         INT NOT NULL DEFAULT 0,
    features           JSONB
);

CREATE TABLE IF NOT EXISTS plan_entitlements (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id            BIGINT NOT NULL REFERENCES subscription_plans(id) ON DELETE CASCADE,
    entitlement_code   VARCHAR(64) NOT NULL,
    value_type         VARCHAR(16) NOT NULL,
    value              VARCHAR(128) NOT NULL,
    UNIQUE (plan_id, entitlement_code)
);

CREATE TABLE IF NOT EXISTS organization_subscriptions (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id         BIGINT NOT NULL REFERENCES organizations(id),
    plan_id                 BIGINT NOT NULL REFERENCES subscription_plans(id),
    status                  VARCHAR(32) NOT NULL,
    stripe_subscription_id  VARCHAR(128),
    current_period_start    TIMESTAMPTZ,
    current_period_end      TIMESTAMPTZ,
    cancel_at_period_end    BOOLEAN NOT NULL DEFAULT FALSE,
    entitlement_overrides   JSONB,
    version                 INT NOT NULL DEFAULT 1,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS usage_counters (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id  BIGINT NOT NULL REFERENCES organizations(id),
    period_start     DATE NOT NULL,
    period_end       DATE,
    metric_code      VARCHAR(64) NOT NULL,
    used_value       NUMERIC(12,2) NOT NULL DEFAULT 0,
    UNIQUE (organization_id, period_start, metric_code)
);

-- ---------------------------------------------------------------------------
-- Trust / CRM / notifications / media / ops
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS reviews (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id         BIGINT NOT NULL REFERENCES businesses(id),
    booking_id          BIGINT NOT NULL UNIQUE REFERENCES bookings(id),
    customer_user_id    BIGINT NOT NULL REFERENCES users(id),
    rating              INT NOT NULL,
    comment             TEXT,
    owner_reply         TEXT,
    owner_replied_at    TIMESTAMPTZ,
    is_visible          BOOLEAN NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ,
    deleted_at          TIMESTAMPTZ
);

ALTER TABLE reviews ADD COLUMN IF NOT EXISTS customer_user_id BIGINT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS owner_reply TEXT;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS owner_replied_at TIMESTAMPTZ;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS is_visible BOOLEAN DEFAULT TRUE;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;
ALTER TABLE reviews ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'reviews' AND column_name = 'customer_id') THEN
        EXECUTE 'UPDATE reviews SET customer_user_id = customer_id WHERE customer_user_id IS NULL';
    END IF;
END $$;
UPDATE reviews SET is_visible = TRUE WHERE is_visible IS NULL;

CREATE TABLE IF NOT EXISTS favorites (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_user_id    BIGINT NOT NULL REFERENCES users(id),
    business_id         BIGINT NOT NULL REFERENCES businesses(id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (customer_user_id, business_id)
);

ALTER TABLE favorites ADD COLUMN IF NOT EXISTS customer_user_id BIGINT;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'favorites' AND column_name = 'customer_id') THEN
        EXECUTE 'UPDATE favorites SET customer_user_id = customer_id WHERE customer_user_id IS NULL';
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS customer_business_notes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id         BIGINT NOT NULL REFERENCES businesses(id),
    customer_user_id    BIGINT NOT NULL REFERENCES users(id),
    author_user_id      BIGINT NOT NULL REFERENCES users(id),
    note                TEXT NOT NULL,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS notifications (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT NOT NULL REFERENCES users(id),
    channel      VARCHAR(32) NOT NULL DEFAULT 'IN_APP',
    title        VARCHAR(255) NOT NULL,
    body         TEXT,
    payload      JSONB,
    is_read      BOOLEAN NOT NULL DEFAULT FALSE,
    sent_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS channel VARCHAR(32) DEFAULT 'IN_APP';
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS body TEXT;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS payload JSONB;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS is_read BOOLEAN DEFAULT FALSE;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS sent_at TIMESTAMPTZ;
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
UPDATE notifications SET channel = 'IN_APP' WHERE channel IS NULL;
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'notifications' AND column_name = 'message') THEN
        EXECUTE 'UPDATE notifications SET body = message WHERE body IS NULL';
    END IF;
END $$;
UPDATE notifications SET is_read = FALSE WHERE is_read IS NULL;

CREATE TABLE IF NOT EXISTS notification_preferences (
    user_id     BIGINT NOT NULL REFERENCES users(id),
    channel     VARCHAR(32) NOT NULL,
    event_type  VARCHAR(64) NOT NULL,
    enabled     BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (user_id, channel, event_type)
);

CREATE TABLE IF NOT EXISTS media_assets (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_type    VARCHAR(32) NOT NULL,
    owner_id      BIGINT NOT NULL,
    storage_key   VARCHAR(512) NOT NULL,
    url           VARCHAR(1024) NOT NULL,
    mime_type     VARCHAR(128),
    bytes         BIGINT,
    sort_order    INT NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS business_media (
    business_id      BIGINT NOT NULL REFERENCES businesses(id) ON DELETE CASCADE,
    media_asset_id   BIGINT NOT NULL REFERENCES media_assets(id) ON DELETE CASCADE,
    role             VARCHAR(32) NOT NULL DEFAULT 'gallery',
    PRIMARY KEY (business_id, media_asset_id)
);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'businesses' AND column_name = 'logo_url') THEN
        EXECUTE $sql$
            INSERT INTO media_assets (owner_type, owner_id, storage_key, url, mime_type, sort_order, created_at)
            SELECT 'BUSINESS', b.id, 'legacy-logo-' || b.id, b.logo_url, 'image/*', 0, NOW()
            FROM businesses b
            WHERE b.logo_url IS NOT NULL AND b.logo_url <> ''
              AND NOT EXISTS (
                  SELECT 1 FROM media_assets m
                  WHERE m.owner_type = 'BUSINESS' AND m.owner_id = b.id AND m.storage_key = 'legacy-logo-' || b.id
              )
        $sql$;
    END IF;
END $$;

INSERT INTO business_media (business_id, media_asset_id, role)
SELECT m.owner_id, m.id, 'logo'
FROM media_assets m
WHERE m.storage_key LIKE 'legacy-logo-%'
ON CONFLICT DO NOTHING;

DO $$
DECLARE
    rec RECORD;
    url TEXT;
    idx INT;
    asset_id BIGINT;
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'businesses' AND column_name = 'gallery_urls') THEN
        FOR rec IN SELECT id, gallery_urls FROM businesses WHERE gallery_urls IS NOT NULL AND gallery_urls <> '' LOOP
            idx := 0;
            FOREACH url IN ARRAY string_to_array(rec.gallery_urls, ',') LOOP
                url := trim(url);
                IF url <> '' THEN
                    INSERT INTO media_assets (owner_type, owner_id, storage_key, url, mime_type, sort_order, created_at)
                    VALUES ('BUSINESS', rec.id, 'legacy-gallery-' || rec.id || '-' || idx, url, 'image/*', idx, NOW())
                    RETURNING id INTO asset_id;
                    INSERT INTO business_media (business_id, media_asset_id, role)
                    VALUES (rec.id, asset_id, 'gallery')
                    ON CONFLICT DO NOTHING;
                    idx := idx + 1;
                END IF;
            END LOOP;
        END LOOP;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS system_settings (
    key          VARCHAR(128) PRIMARY KEY,
    value        JSONB NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by   BIGINT REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS audit_events (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id     BIGINT REFERENCES users(id),
    organization_id   BIGINT REFERENCES organizations(id),
    business_id       BIGINT REFERENCES businesses(id),
    action            VARCHAR(128) NOT NULL,
    entity_type       VARCHAR(64),
    entity_id         BIGINT,
    before_state      JSONB,
    after_state       JSONB,
    ip_address        VARCHAR(64),
    user_agent        VARCHAR(512),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'audit_logs') THEN
        EXECUTE $sql$
            INSERT INTO audit_events (actor_user_id, action, entity_type, entity_id, ip_address, created_at)
            SELECT user_id, action, entity, entity_id, ip_address, COALESCE(timestamp, NOW())
            FROM audit_logs
        $sql$;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS feature_flags (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(128) NOT NULL UNIQUE,
    description          VARCHAR(255),
    is_enabled_global    BOOLEAN NOT NULL DEFAULT FALSE,
    rules                JSONB
);

-- Copy leftover system_configs into key/value settings
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'system_configs') THEN
        EXECUTE $sql$
            INSERT INTO system_settings (key, value, updated_at)
            SELECT 'registration_open', to_jsonb(is_registration_open), NOW()
            FROM system_configs
            LIMIT 1
            ON CONFLICT (key) DO NOTHING
        $sql$;
        EXECUTE $sql$
            INSERT INTO system_settings (key, value, updated_at)
            SELECT 'supported_currencies', to_jsonb(supported_currencies), NOW()
            FROM system_configs
            LIMIT 1
            ON CONFLICT (key) DO NOTHING
        $sql$;
    END IF;
END $$;

INSERT INTO system_settings (key, value, updated_at)
VALUES
    ('registration_open', 'true'::jsonb, NOW()),
    ('default_currency', '"USD"'::jsonb, NOW()),
    ('supported_currencies', '"USD,PKR,AED,EUR,GBP"'::jsonb, NOW())
ON CONFLICT (key) DO NOTHING;

-- staff FK for member_roles now that staff exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'member_roles_staff_id_fkey'
    ) THEN
        ALTER TABLE member_roles
            ADD CONSTRAINT member_roles_staff_id_fkey
            FOREIGN KEY (staff_id) REFERENCES staff(id);
    END IF;
END $$;

-- ---------------------------------------------------------------------------
-- Drop legacy columns / tables that would fight the new mapping
-- ---------------------------------------------------------------------------
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users DROP COLUMN IF EXISTS role;
ALTER TABLE users DROP COLUMN IF EXISTS active;
DROP TYPE IF EXISTS user_role_enum;

ALTER TABLE businesses DROP CONSTRAINT IF EXISTS businesses_owner_id_fkey;
ALTER TABLE businesses DROP COLUMN IF EXISTS owner_id;
ALTER TABLE businesses DROP COLUMN IF EXISTS commission_rate;
ALTER TABLE businesses DROP COLUMN IF EXISTS rating;
ALTER TABLE businesses DROP COLUMN IF EXISTS verified;
ALTER TABLE businesses DROP COLUMN IF EXISTS logo_url;
ALTER TABLE businesses DROP COLUMN IF EXISTS gallery_urls;

ALTER TABLE branches DROP COLUMN IF EXISTS geom;

ALTER TABLE staff DROP COLUMN IF EXISTS rating;

ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_customer_id_fkey;
ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_service_id_fkey;
ALTER TABLE bookings DROP CONSTRAINT IF EXISTS fkd46pbw7jv4bm2xdcxmt36dti8;
ALTER TABLE bookings DROP COLUMN IF EXISTS customer_id;
ALTER TABLE bookings DROP COLUMN IF EXISTS service_id;
ALTER TABLE bookings DROP COLUMN IF EXISTS staff_id;
ALTER TABLE bookings DROP COLUMN IF EXISTS price;

ALTER TABLE customer_packages DROP CONSTRAINT IF EXISTS customer_packages_customer_id_fkey;
ALTER TABLE customer_packages DROP COLUMN IF EXISTS customer_id;

ALTER TABLE reviews DROP CONSTRAINT IF EXISTS reviews_customer_id_fkey;
ALTER TABLE reviews DROP COLUMN IF EXISTS customer_id;

ALTER TABLE favorites DROP CONSTRAINT IF EXISTS favorites_customer_id_fkey;
ALTER TABLE favorites DROP COLUMN IF EXISTS customer_id;

ALTER TABLE notifications DROP COLUMN IF EXISTS message;

DROP TABLE IF EXISTS business_secondary_categories;
DROP TABLE IF EXISTS breaks;
DROP TABLE IF EXISTS working_hours;
DROP TABLE IF EXISTS holidays;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS system_configs;

CREATE UNIQUE INDEX IF NOT EXISTS uk_system_roles_code ON roles (code) WHERE is_system;
CREATE UNIQUE INDEX IF NOT EXISTS uk_users_email_active ON users (email) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_businesses_organization ON businesses (organization_id);
CREATE INDEX IF NOT EXISTS idx_businesses_status_verified ON businesses (status, is_verified);
CREATE INDEX IF NOT EXISTS idx_branches_business ON branches (business_id);
CREATE INDEX IF NOT EXISTS idx_branches_lat_lon ON branches (latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_services_business_active ON services (business_id, is_active);
CREATE INDEX IF NOT EXISTS idx_bookings_branch_time ON bookings (branch_id, booking_time);
CREATE INDEX IF NOT EXISTS idx_bookings_customer_time ON bookings (customer_user_id, booking_time);
CREATE INDEX IF NOT EXISTS idx_bookings_business_status ON bookings (business_id, status);
CREATE INDEX IF NOT EXISTS idx_booking_items_staff_time ON booking_items (staff_id, start_time, end_time);
CREATE INDEX IF NOT EXISTS idx_member_roles_user ON member_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_member_roles_org_user ON member_roles (organization_id, user_id);
CREATE INDEX IF NOT EXISTS idx_payments_provider ON payments (provider_payment_id);
CREATE INDEX IF NOT EXISTS idx_payments_reference ON payments (reference_type, reference_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_created ON audit_events (created_at);
CREATE INDEX IF NOT EXISTS idx_audit_events_entity ON audit_events (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user ON notifications (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_waitlist_branch_status ON waitlist_entries (branch_id, status, preferred_start);

DROP FUNCTION IF EXISTS hourslot_rename_column(text, text, text);
