-- Business KYC documents (minimal 3) + staff invite tokens.

CREATE TABLE IF NOT EXISTS business_verification_documents (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id          BIGINT NOT NULL REFERENCES businesses(id),
    document_type        VARCHAR(64) NOT NULL,
    media_asset_id       BIGINT NOT NULL REFERENCES media_assets(id),
    original_filename    VARCHAR(255),
    status               VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED',
    review_notes         TEXT,
    reviewed_by_user_id  BIGINT REFERENCES users(id),
    reviewed_at          TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ,
    deleted_at           TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_biz_verif_doc_active
    ON business_verification_documents (business_id, document_type)
    WHERE deleted_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_biz_verif_docs_business
    ON business_verification_documents (business_id)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS staff_invites (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organization_id      BIGINT NOT NULL REFERENCES organizations(id),
    business_id          BIGINT NOT NULL REFERENCES businesses(id),
    branch_id            BIGINT NOT NULL REFERENCES branches(id),
    email                VARCHAR(255) NOT NULL,
    display_name         VARCHAR(255) NOT NULL,
    designation          VARCHAR(128),
    token_hash           VARCHAR(128) NOT NULL UNIQUE,
    status               VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    invited_by_user_id   BIGINT REFERENCES users(id),
    expires_at           TIMESTAMPTZ NOT NULL,
    accepted_at          TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_staff_invites_org_status
    ON staff_invites (organization_id, status);

CREATE INDEX IF NOT EXISTS idx_staff_invites_email
    ON staff_invites (LOWER(email));
